### ISSUE TITLE
Trackback Errors

### ISSUE THREAD

**Issue by ghost** [bjanes0/fplbythebooks#1]
Getting trackback errors on following 
![image](https://user-images.githubusercontent.com/50903319/63481328-1705ab80-c4d0-11e9-9dd5-34c3cad61c50.png)

**Comment by bjanes0** [comment]
Currently the client needs data in the form of a CSV with a first_name, second_name, goal_percent, assist_percent and cs_percent, you are receiving an error as you do not have the sample data CSV. I will be updating the client soon such that you can receive an accurate and complete projection with one script.

**Comment by bjanes0** [comment]
The client has been updated and no longer requires any input files.
